== Utilisation des modules

<<<

=== Le "scope" global

*_Rappel_* +
JavaScript dispose d'un "scope" global, il s'agit d'un +object+ disposant déjà d'un certain nombre de propriétés et de méthodes.

*_Dans un navigateur_* +
```js
console.log(window);
console.log(this);
```

C'est également vrai pour Node.js qui a un "scope" global se nommant +global+.

*_Dans Node.js_* +
```js
console.log(global);
console.log(this);
```

<<<

=== Modules en JavaScript

Dans Node.js (comme dans un navigateur) il faut limiter l'utilisation du "scope" global pour éviter les risques de collision et optimiser l'usage de la mémoire.

```js
console.log(global.newSideEffect);
newSideEffect = 42;
console.log(global.newSideEffect);
```

*_Rappel_* +
Le fonctionnement des "closures" et des IIFE permettent l'exposition publique vs privée de propriétés d'un objet.

Sur le même principe d'isolement de "scope" que les IIFE, Node.js dispose d'un système de modules natif qui permet de limiter la portée des "scopes" tout en laissant la possibilité d'exporter des états, des fonctions, etc.

Il s'avère qu'il existe plusieurs système de modules, Node.js a commencé avec (et peut toujours utiliser) la syntaxe CommonJS.

<<<

=== CommonJS

http://www.commonjs.org/[CommonJS] peut être perçu comme une API pour normaliser et simplifier l'utilisation de modules dans les environnements JavaScript. Elle est implémentée par défaut au sein de Node.js.

On peut ainsi facilement exporter depuis un autre fichier un +object+ pouvant contenir des valeurs en JavaScript avec le mot clé +exports+.

```js
// mathTools.js
exports.add = (a, b) => a + b;
```

Puis importer cette valeur depuis le fichier avec le mot clé +require+.

```js
// program.js
require('./mathTools').add(4, 7); // 11
```
NOTE: L'extension du fichier ".js" est facultative pour les imports.

<<<

=== Modules présents par défaut

Certains modules sont présents nativement au sein de Node.js, les principaux étant :

- https://nodejs.org/api/fs.html[fs] : Module "File System" pour créer / modifier / supprimer des fichiers
- https://nodejs.org/api/net.html[net] : Module pour utiliser les protocoles TCP ou IPC
- https://nodejs.org/api/http.html[http] : Module pour utiliser le protocole HTTP
- https://nodejs.org/api/path.html[path] : Module pour travailler sur les chemins des fichiers / répertoires
- https://nodejs.org/api/events.html[events] : Module pour appliquer la programmation événementielle

```js
const http = require('http')

http.get('http://numbersapi.com/42', (res) => {
  res.setEncoding('utf8')
  res.on('data', fact => console.log(fact))
});
```
