
=== Installer un module via npm

Dans une invite de commandes, l'instruction +npm install+ permet d'installer un module. Il existe 2 manières d'installer un module, soit de manière locale au projet (option par défaut), soit de manière globale (avec l'option +-g+).

```shell

// local
npm install <module_name>

// global
npm install -g <module_name>

```

Dans le premier cas, le module sera installé depuis le répertoire courant où l'instruction a été lancée. Il ne sera donc accessible que depuis ce répertoire courant.

Dans le deuxième cas, le module sera installé dans un répertoire commun lié à l'installation de Node. Il sera donc accessible depuis n'importe quel répertoire de l'environnement.

<<<

=== Installer tous les modules

Lors d'installations locales de modules, npm va rapatrier ceux-ci dans un répertoire +node_modules+.

Pour installer au pré-requis tous les modules nécessaires au bon fonctionnement d'un projet, npm va s'appuyer sur le fichier +package.json+ qui liste les dépendances (et leurs versions associées) avec +dependencies+, +devDependencies+, +optionnalDependencies+ et +peerDependencies+.

Il suffit ensuite d'executer +npm install+ dans le répertoire où se situe le fichier +package.json+ pour installer toutes les dépendances listées dans le répertoire +node_modules+.

```shell

npm install

```

<<<

=== Le fichier +package.json+

Le fichier +package.json+ est le point d'entrée de tout projet/module devant s'exécuter dans Node.js, il contient principalement :

- Les informations relatives au projet : +name+, +description+, +version+, +license+, +contributors+, etc.

- Les dépendances : +dependencies+, +devDependencies+, +optionnalDependencies+ et +peerDependencies+.

- Les exécutions possibles avec +scripts+.

- Les contraintes de compatibilité Node.js avec +engines+.

Il existe beaucoup d'autres informations que l'on peut renseigner dans ce fichier, https://docs.npmjs.com/files/package.json[la documentation officielle] exhaustive à ce sujet.

<<<

=== Un exemple de +package.json+

```js

{
  "name": "colourfull-api",
  "version": "1.0.5",
  "description": "Web API to deliver palettes of colours.",
  "dependencies": {
    "body-parser": "1.5.2",
    "cors": "2.8.1",
    "express": "4.2.0"
  },
  "devDependencies": {
    "expect.js": "0.3.1",
    "mocha": "1.21.0",
    "superagent": "0.18.2"
  },
  "scripts": {
    "start": "node index.js",
    "test": "mocha --timeout 15000 test/"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/my-company/colourfull-api"
  },
  "license": "MIT license"
}

```

<<<

=== Enrichir un fichier +package.json+

TIP: La commande +npm init+ permet de générer facilement un fichier +package.son+.

Une fois le fichier +package.json+ créé il conviendra de le mettre à jour régulièrement, notamment sur les dépendances nécessaires au projet. Des options sont disponibles en ce sens.

```shell

// depencies
npm install --save <module_name>

// devDepencies
npm install --save-dev <module_name>

// optionnalDepencies
npm install --save-optionnal <module_name>

```

<<<

=== (Bien) enrichir un fichier +package.json+

Par défaut les commandes +npm install+ ne gèlent pas les dépendances de manière stricte, mais en utilisant +^version+ qui correspond à "Compatible with version" (cf. https://docs.npmjs.com/files/package.json[documentation officielle]).

```js

// package.json
...
  "dependencies": {
    "express": "^4.14.0"
  }
...

```

Honnêtement mieux vaut se passer de ce fonctionnement par défaut et geler strictement toutes les dépendances.

C'est posible facilement avec l'option supplémentaire +--save-exact+.

```shell

npm install --save --save-exact <module_name>

```

<<<

=== Utiliser un module

L'utilisation des modules dans Node.js se fait via https://nodejs.org/docs/latest/api/modules.html[CommonJS]. L'import de modules est réalisé avec la commande +require+, il est ainsi possible d'utiliser les modules récupérés de npm, tout comme ses propres modules.

```js

// modules from npm
var express = require('express');
var cors = require('cors');
var bodyParser = require('body-parser');

// custom modules
var routes = require('./routes/index');

var app = express();

...

// URL mapping
app.use('/', routes);

app.listen(3000, function () {
  console.log('Server started on port 3000')
});

```

<<<

=== Gèrer les modules

La gestion des modules est une tâche importante pour s'assurer qu'un projet sera opérationnel.

Il ne suffit pas de voir fonctionner un projet sur son environnement local.

Plusieurs commandes npm nous aide en ce sens.

```shell

// Supprime les modules locaux non déclarés dans package.json
npm prune

// Référencement des modules qui devraient être installés ou mis à jour
npm outdated

// Mise à jour des modules
npm update

```





